### ISSUE TITLE
Flooding protection

### ISSUE THREAD

**Issue by natrius** [the-draupnir-project/Draupnir#209]
We have to deal with users flooding the room. What would be usefull in my opinion is a flooding protection similar to wordlist. What i could think of as setting for that would be like that:

```
# Configuration specific to certain toggle-able protections
protections:
  # Configuration for the wordlist plugin, which can ban users based if they say certain
  # blocked words shortly after joining.
  flooding:
    # Message in x time for flooding protection. Time set with the next parameter.
    messagesCountForFlooding: 10

    # Time for the message-count above for the flooding protection
    messagesTimeForFlooding: 1

    # Action that should be done. Available: channelwritepermissions; userpermission; userban; 
    # channelwritepermissions sets the channel permissions to write to 1
    # userpermissions sets the write permissions for the user to -1
    # userban bans the user in question
    actionForFlooding: userban

    # For how long (in minutes) the user is "new" to the flooding plugin.
    #
    # After this time, the user will no longer be banned for writing more than x message in the timeframe specified below
    #
    # Set to zero to disable the timeout and make users *always* appear "new".
    # (users will always be banned if they write more messages in the timeframe set below)
    minutesBeforeTrusting: 20
```
