### ISSUE TITLE
Draupnir can't parse reports when using `pollReports`

### ISSUE THREAD

**Issue by mtippmann** [the-draupnir-project/Draupnir#839]
**How is Draupnir setup?**

install - verbatim: https://the-draupnir-project.github.io/draupnir-documentation/bot/setup_debian

`production.yaml`: 

```
homeserverUrl: "https://matrix.bau-ha.us"
rawHomeserverUrl: "https://matrix.bau-ha.us"

accessToken: "..."
pantalaimon:
  use: false

experimentalRustCrypto: false
dataPath: "/opt/mod-bot/Draupnir/datastorage"
autojoinOnlyIfManager: true
acceptInvitesFromSpace: "!example:example.org"
recordIgnoredInvites: false
logLevel: "INFO"
verifyPermissionsOnStartup: true
noop: false
disableServerACL: false
automaticallyRedactForReasons:
  - "spam"
  - "advertising"
protectAllJoinedRooms: false
backgroundDelayMS: 500
admin:
  enableMakeRoomAdminCommand: true

commands:
  allowNoPrefix: false
  additionalPrefixes:
    - "draupnir"
  ban:
    defaultReasons:
      - "spam"
      - "brigading"
      - "harassment"
      - "disagreement"

protections:
  wordlist:
    words:
      - "LoReM"
      - "IpSuM"
      - "DoLoR"
      - "aMeT"

    minutesBeforeTrusting: 20

roomStateBackingStore:
  enabled: true


..
web:
  enabled: true

  port: 9001

  address: localhost


  abuseReporting:
    enabled: false
  synapseHTTPAntispam:
    enabled: true
    authorization: ...

pollReports: true

displayReports: true
``` 

**What were you trying to achieve?**

I attempted to use the `pollReports` option because setting up nginx was a little bit more involved and it crashed when attempting to get reports - in synapse-admin I can see the reports 

**What steps did you take to encounter the bug**

Setting up polling, restarting draupnir - waiting a bit and then the exception come in. 

**What is the bug or what did you expect to happen instead?**

expectation: getting reports stored in synapse 

reality - parsing error: 

```
‼ | failed to poll events: ActionException: 7eebafcf-60af-41c8-a6a2-542a8ce05844
Unable to decode an event\nfrom error: Error: Unable to decode value as it does not match the expected schema
Error: Unable to decode value as it does not match the expected schema
    at TypeCheck.Decode (/opt/mod-bot/Draupnir/node_modules/@sinclair/typebox/build/cjs/compiler/compiler.js:59:19)
    at Value.Decode (/opt/mod-bot/Draupnir/node_modules/matrix-protection-suite/dist/Interface/Value.js:38:45)
    at SynapseAdminClient.getAbuseReports (/opt/mod-bot/Draupnir/node_modules/matrix-protection-suite-for-matrix-bot-sdk/dist/SynapseAdmin/SynapseAdminClient.js:122:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ReportPoller.getAbuseReports (/opt/mod-bot/Draupnir/lib/report/ReportPoller.js:62:26)
    at async ReportPoller.tryGetAbuseReports (/opt/mod-bot/Draupnir/lib/report/ReportPoller.js:111:13)",
```
